geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp
app_name = 'mainapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='index'),
    path('add/<int:pk>', basketapp.basket_add, name='add'),
    path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
import adminapp.views as adminapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя продукта', max_length=64, unique=True)
    discription = models.TextField(verbose_name='Описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    # created = models.DateTimeField(auto_now_add=True)
    # updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=64,
    )
    image = models.ImageField(
        upload_to='media',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='короткое описание',
        max_length=60,
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='Количество на складе',
        default=0
    )

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
from .models import ProductCategory, Product

main_menu = [
    {'href': '/', 'name': 'Домой'},
    {'href': 'products', 'name': 'Продукты'},
    {'href': 'contact', 'name': 'Контакты'},
]


def main(request):
    title = 'Главная'
    products = Product.objects.all()[:4]
    context = {
        'title': title,
        'main_menu': main_menu,
        'products': products
    }
    return render(request, 'mainapp/index.html', context=context, )


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_products():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)

    return same_products


def products(request, pk=None, page=1):
    title = 'Каталог'
    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)
    hot_products = get_hot_products()
    same_products = get_same_products(hot_products)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'pk': 0, 'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        paginator = Paginator(products, 1)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'links_menu': links_menu,
            'main_menu': main_menu,
            'category': category,
            'products': products_paginator,
            'hot_products': hot_products,
            'same_products': same_products,
            'basket': basket,
        }
        return render(request, 'mainapp/products.html', context=context)

    context = {
        'title': title,
        'links_menu': links_menu,
        'main_menu': main_menu,
        'hot_products': hot_products,
        'same_products': same_products,
        'basket': basket,
    }
    return render(request, 'mainapp/products.html', context=context)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'main_menu': main_menu,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = 'Контакты'
    context = {
        'title': title,
        'main_menu': main_menu,
    }
    return render(request, 'mainapp/contact.html', context=context)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
	<title>{{ title|title }}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% block css %}
    {% endblock %}

</head>
<body>
{% block content %}
{% endblock %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}
<html>
<head>
</head>
<body>
{% block content %}
	<div class="container">
		<div class="hero">
			{% include 'mainapp/includes/main_menu.html' %}
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	
{% endblock %}
			
</body>
</html>

geekshop/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}
<html>
<head>
</head>
<body>
{% block content %}
	<div class="container">
		<div class="slider">
				{% include 'mainapp/includes/main_menu.html' %}
			<div class="text-slider">
				<h3 class="green">тенденции {% now "Y" %}</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png'%}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
  				<div class="block">
    				<a href="#"><img src="/media/{{ product.image }}" alt="">
      					<div class="text">
        					<img src="{% static '/img/icon-hover.png' %}" alt="img">
        					<h4>{{ product.name }}</h4>
        					<p>{{ product.short_desc }}</p>
      					</div>
    				</a>
  				</div>
				{% endfor %}
			</div>
		</div>
		
		<div class="clr"></div>

	</div>
{% endblock %}
	
</body>
</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/main_menu.html' %}
        </div>
    </div>
  <div class="details">
    <div class="links clearfix">
				<ul class="links-menu">
					  <li>
						  <a href="{% url 'products:category' 0 %}"
							 class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">все
						  </a>
					  </li>
					{% for link in links_menu %}
					<li>
						  	<a href="{% url 'products:category' link.pk %}"
							 	class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
									  	active
										{% endif %}">
								{{ link.name }}
						  	</a>
							</li>
					  {% endfor %}
				</ul>
			</div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}
<html>
<head>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
{% block css %}

{% endblock %}

{% block content %}
	<div class="container">
		<div class="hero-white">
			{% include 'mainapp/includes/main_menu.html' %}
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					  <li>
						  <a href="{% url 'products:category' 0 %}"
							 class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">все
						  </a>
					  </li>
					{% for link in links_menu %}
					<li>
						  	<a href="{% url 'products:category' link.pk %}"
							 	class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
									  	active
										{% endif %}">
								{{ link.name }}
						  	</a>
							</li>
					  {% endfor %}
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{{ hot_products.image.url }}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{hot_products.name}}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> {{hot_products.price}} <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">{{hot_products.description}}</div>
				</div>
			</div>


			<div class="products_list">
				<div class="title clearfix">
					<h2>Категория: "{{ category.name|title }}"</h2>
					<div class="paginator">

                      {% if products.has_previous %}
                          <li class="page-item"><a class="page-link" href="{% url 'products:page' category.pk products.previous_page_number %}"">Previous</a></li>
                      {% endif %}
                      <span class="current">
                        страница {{ products.number }} из
                        {{ products.paginator.num_pages }}
                      </span>
                      {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">
                          >
                        </a>
                      {% endif %}
                    </div>
				</div>
      			<div class="category-products clearfix">
					{% for product in products %}
					<div class="block">
						<a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="product">
							<div class="text">
								<img src="{% static '/img/icon-hover.png' %}" alt="hover">
								<h4>{{ product.name }}</h4>
								<p>{{ product.short_desc }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
				</div>

<!--				<div class="title clearfix">-->
<!--					<h2>Похожие продукты</h2>-->
<!--					<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>-->
<!--				</div>-->
<!--				<div class="related-products clearfix">-->
<!--					{% for product in products %}-->
<!--					<div class="block">-->
<!--						<a href="#"><img src="/media/{{ product.image }}" alt="">-->
<!--							<div class="text">-->
<!--								<img src="{% static '/img/icon-hover.png' %}" alt="img">-->
<!--								<h4>{{ product.name }}</h4>-->
<!--								<p>{{ product.short_desc }}</p>-->
<!--							</div>-->
<!--						</a>-->
<!--					</div>-->
<!--				{% endfor %}-->
<!--				</div>-->
			</div>
		</div>

		<div class="clr"></div>

	</div>
{% endblock %}

</body>
</html>